# Generated by Django 4.0.3 on 2022-08-18 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='time_end',
            field=models.TimeField(verbose_name='End time to send message'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='time_start',
            field=models.TimeField(verbose_name='Start time to send message'),
        ),
    ]
